<<<<<<< HEAD

/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.4 EDK_O.87xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Configurations for Standalone BSP
*
*******************************************************************/

#define MICROBLAZE_PVR_NONE
=======

/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.4 EDK_O.87xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Configurations for Standalone BSP
*
*******************************************************************/

#define MICROBLAZE_PVR_NONE
>>>>>>> 46133ae2d6a022a717e89ee90e8959352f12048c
